# Generated by Django 4.1.3 on 2022-11-06 01:27

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("domain", models.CharField(max_length=255)),
                ("http_host", models.CharField(max_length=255, null=True)),
                ("remote_host", models.CharField(max_length=255, null=True)),
                ("server_name", models.CharField(max_length=255, null=True)),
                (
                    "user",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="login",
            index=models.Index(
                django.db.models.functions.text.Lower("domain"), name="email_domain_idx"
            ),
        ),
    ]
