# Generated by Django 4.1.3 on 2022-11-06 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_login_login_email_domain_idx"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="login",
            managers=[],
        ),
        migrations.AlterField(
            model_name="login",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
